#! /bin/bash
sudo apt-get remove docker docker-engine docker.io                                      ---- régi Docker verzió eltávolítása
sudo apt-get update
sudo apt-get install \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add 
sudo apt-key fingerprint 0EBFCD88 

sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
sudo apt-get update
sudo apt-get install docker-ce

cd ..
echo -e 'FROM nginx:latest\n RUN rm /usr/share/nginx/html/*\n COPY web /usr/share/nginx/html\n Expose 80 443\n cmd ["nginx", "-g", "daemon off;"]' >Dockerfile

mkdir web
cd web
echo -e 'hello' > index.html
cd ..
sudo docker build -t new .

sudo adduser ubuntu docker
uname -r
sudo apt-get update -y
sudo docker run -d --name docker-nginx -p 80:80 new
